= Install and Get Started with Couchbase Service Broker on Kubernetes

[abstract]
This section describes how to get and install the service broker and create your first service instance.

ifdef::env-github[]
:relfileprefix: ../
:imagesdir: https://github.com/couchbase/service-broker/raw/master/documentation/modules/ROOT/assets/images
endif::[]

The Service Broker is just a simple web-service that creates Kubernetes resources on demand as requested by the API.
This Getting Started tutorial will take you through the following steps to install and get started with Couchbase Service Broker on Kubernetes:

. Prerequisites
. Download packages
. Install Couchbase Service Broker
. Create Couchbase Cluster
. Register the service and create your first service instance.


== Prerequisites

This page details the platform and software requirements for running the Service Broker.

=== Kubernetes Cluster

The following platforms are supported:

•	Kubernetes 1.17+
•	Red Hat OpenShift 4.4+

In general, any Kubernetes distribution based on a supported version should work.

=== Kubernetes Service Catalog

The Service Broker is recommended for use with the Kubernetes Service Catalog.
Installation instructions can be found in the official documentation.
As the Service Broker is standards based, any version of the Service Catalog supporting the Open Service Broker API version 2.13+ is supported.

=== Couchbase Autonomous Operator

Install Operator from xref:operator:install-kubernetes.adoc[here].

== Package Downloads 

Download Couchbase Service Broker https://www.couchbase.com/downloads[package] and unpack on the same computer where you normally run kubectl.

The Couchbase Service Broker package contains YAML configuration files and command-line tools that you will use to install the Couchbase Service Broker and Couchbase Clusters.

== Install Couchbase Service Broker

IMPORTANT: After you unpack the downloaded package, the resulting directory will be titled something like couchbase-service-broker_x.x.x. Make sure to `cd` into this directory before you run the remaining commands in this guide.

=== Install the CRD

The Service Broker is configured using a Kubernetes Custom Resource that allows type checking of your configurations and must be installed first:

[source,console]
----
$ kubectl create -f crd.yaml
----

=== Install a Configuration

[source,console]
----
$ kubectl create -f servicebrokerconfig.yaml
----

=== Install the Service Broker Service

[source,console]
----
$ kubectl create -f broker.yaml
----

The ServiceAccount the Service Broker runs as is bound to the Role we created in the previous step. A Secret contains the TLS configuration and bearer token for authentication as the Service Broker is secure by default. The Deployment creates the Service Broker and ensures it is highly available and a Service makes it discoverable by the Kubernetes Service Catalog in the next step.
Check the status of the service broker

[source,console]
----
$ kubectl get deployments

NAME                          	 	READY   	UP-TO-DATE   AVAILABLE   	AGE
couchbase-operator            		 1/1     		1            	1        	33m
couchbase-operator-admission   		 1/1     		1             1        	37m
couchbase-service-broker       		 1/1     		1            	1         32m
----

=== Register the Service Broker with the Service Catalog

The final step is to tell the Kubernetes Service Catalog about our Service Broker. 

[source,console]
----
$ kubectl create -f clusterservicebroker.yaml
----

== Create Couchbase Cluster

=== Provision the Couchbase Cluster Service:

[source,console]
----
$ svcat provision csb --class couchbase-osb-service --plan csb-basic --param password=password --wait
----

You will end up with a 3 node cluster (by default), with a Bucket, an Administrator user with the password you provided.

=== Bind to the Provisioned Service

[source,console]
----
$ svcat bind csb

Name:        csb 
    Namespace:   default  
    Status:               
    Secret:      csb  
    Instance:    csb  
  
  Parameters:
    No parameters defined
----    

This will create a user and allow access to the bucket.  Connection string, username, password and CA certificate will be in the secret, ready to be used by a client of some variety.

[source,console]
----
$ kubectl get secrets csb
NAME   TYPE     DATA   AGE
csb    	Opaque       5      7m58s
----

To access the couchbase cluster UI console: 

[source,console]
----
$ kubectl port-forward couchbase-instance-winhhoku-0000 8091
----

Go to http://localhost:8091 and login with username as Administrator & password as password.

// The following example demonstrates how to deploy a Couchbase cluster on your local with Couchbase Service Broker from scratch.
