= Try out the Couchbase Service Broker Locally with Minikube
include::partial$constants.adoc[]

[abstract]
Using a local minikube environment, learn how to use the Couchbase Service Broker to deploy a Couchbase cluster and the Couchbase Autonomous Operator.

== Introduction

In this tutorial you'll learn how to use the Couchbase Service Broker to deploy instances of Couchbase clusters and the Couchbase Autonomous Operator.

[[before-you-begin]]
== Before You Begin

Before you begin this tutorial, you'll need to set up a few things first:

* Install the latest https://hub.docker.com/[Docker Desktop^] release for your current platform.
You'll need this installed and running in order to install minikube.
** Make sure to set Docker resource settings to have at least 8 GB (8192 Mi) of memory.

* Install the latest https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl^] for your current platform.
If `kubectl` is already installed, it gets configured to access the Kubernetes cluster control plane inside minikube when the `minikube start` command is executed.
** Alternatively, if `kubectl` is not installed locally, you can use the version of `kubectl` included with minikube (after it is installed) by aliasing it as follows:
+
--
[source,console]
----
alias kubectl="minikube kubectl --"
----
--

* Install the latest https://svc-cat.io/docs/install/#installing-the-service-catalog-cli[Service Catalog CLI^] for your current platform.

* Install the latest https://helm.sh/docs/intro/install/[Helm] release for your current platform.
You'll be using this to install some necessary dependencies.

* Install the latest https://minikube.sigs.k8s.io/docs/start/[minikube^] for your current platform.

== Create a Local Kubernetes Cluster

With Docker running, create a Kubernetes cluster using minikube.

[source, bash]
----
$ minikube start --cpus 2 --memory 8192
----

If you encounter error about not having enough memory, make sure that you've set Docker resources to at least 8 GB of memory.

== Install the Service Catalog

Now that you have a single-node Kubernetes cluster running on your computer, it's time to https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/[install the service catalog using Helm].

Start by adding the service-catalog Helm repository:

[source,console]
----
$ helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog
----

You can verify the installation with the following command:

[source,console]
----
$ helm search repo service-catalog
----
----
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                       
svc-cat/catalog     	0.3.1        	           	service-catalog webhook server and controller-m...
svc-cat/catalog-v0.2	0.2.3        	           	service-catalog API server and controller-manag...
----

Now that the chart repository has been added, it's time to install the chart.

[source,console]
----
$ helm install catalog svc-cat/catalog --namespace catalog --create-namespace
----

== Download and Install Service Broker Dependencies

Before you can proceed with rest of the steps in this guide, you'll need to download the necessary packages from https://www.couchbase.com/downloads[couchbase.com/downloads^].

Please download the following packages:

* *Couchbase Service Broker {service-broker-version-minor}*
* *Couchbase Autonomous Operator 2.2*

Both of these packages contain YAML configuration files and command-line tools that you will use to install the Couchbase Service Broker and Couchbase Clusters.

IMPORTANT: Make sure to unpack these packages on the same computer where you normally run `kubectl`.

=== Install `cbopcfg`

The Couchbase _Autonomous Operator_ package includes a command-line tool named `cbsbctl`, which is used to install certain dependencies for the Autonomous Operator.
Use the steps below to install `cbopcfg` on your platform of choice.

include::partial$tools-install.adoc[tags=cbopcfg]

=== Install the Autonomous Operator CRDs and Dynamic Admission Controller

The included service plans deploy instances of the Autonomous Operator, which has its own dependencies.

From the unpacked _Autonomous Operator_ directory, run the following command to install the Autonomous Operator CRD:

[source,console]
----
$ kubectl create -f crd.yaml
----

Next, run the following command to install the dynamic admission controller (DAC) into the `default` namespace.

[source,console]
----
$ cbopcfg create admission
----

=== Install `cbcsctl`

The Couchbase _Service Broker_ package includes a command-line tool named `cbsbctl`, which is used during installation.
Use the steps below to install `cbsbctl` on your platform of choice.

include::partial$tools-install.adoc[tags=cbsbctl]

=== Install the Service Broker CRD

The Service Broker is configured using a Kubernetes custom resource that allows type checking of your configurations.
In order to use this custom resource, you must install the custom resource definition (CRD) that is included in the Service Broker package download.

From the unpacked _Service Broker_ directory:

[source,console]
----
$ kubectl create -f crd.yaml
----

== Install the Service Broker

The Service Broker can be installed at the namespace level or the cluster level.
For the purposes of this tutorial, we'll be installing the Service Broker at the cluster level.

From the unpacked _Service Broker_ directory:

[source,console]
----
$ ./cbsbctl create clusterservicebroker --profile demo
----

You can run the following command to check the status of the Service Broker:

[source,console]
----
$ kubectl get deployments
----
----
NAME                          	 	READY   	UP-TO-DATE   AVAILABLE   	AGE
couchbase-operator-admission   		 1/1     		1             1        	37m
couchbase-service-broker       		 1/1     		1            	1         32m
----

== Provision the Couchbase Cluster Service

The following command deploys a three-node cluster (by default), with a Bucket, and an Administrator user with a password.

[source,console]
----
$ svcat provision csb --class cao-2.2-service --plan csb-basic --param password=password --wait
----

== Bind to the Provisioned Service

[source,console]
----
$ svcat bind csb
----
----
Name:        csb
    Namespace:   default
    Status:
    Secret:      csb
    Instance:    csb

  Parameters:
    No parameters defined
----

This will create a user and allow access to the bucket.
Connection string, username, password, and CA certificate will be in the secret, ready to be used by a client of some variety.

[source,console]
----
$ kubectl get secrets csb
----
----
NAME   TYPE     DATA   AGE
csb    	Opaque       5      7m58s
----

To access the Couchbase Web Console:

[source,console]
----
$ kubectl port-forward couchbase-instance-winhhoku-0000 8091
----

Go to `http://localhost:8091` and login with the credentials used when provisioning the Couchbase cluster service.
