= Release Notes for Couchbase Service Broker {service-broker-version-minor}
include::partial$constants.adoc[]

The Couchbase Service Broker provides native integration of the Couchbase Autonomous Operator with the https://www.openservicebrokerapi.org/[Open Service Broker API^] for Open Source Kubernetes .

== Installation

For installation instructions, refer to:

* xref:install/get-started.adoc[]

[#release-v120]
== Release 1.2.0

Couchbase Service Broker 1.2.0 was released in April 2022.

[#supported-platforms-v120]
=== Platform Support

Couchbase Service Broker 1.2.0 supports Kubernetes 1.17-1.21, including managed Kubernetes platforms AWS EKS, Azure AKS, and Google GKE.

Note that Red Hat OpenShift is not supported, as Template Service Broker and Service Catalog have been deprecated and removed from the latest OpenShift releases.

For a list of currently supported platforms, refer to xref:install/get-started.adoc#prerequisites[Prerequisites].

[#changes-in-behavior-v120]
=== Major Behavior Changes and Enhancements

==== New Service Classes

Couchbase Service Broker 1.2.0 provides the following service classes:

* Class: `cao-2.1-service`
** Plan: `csb-basic`
** Plan: `csb-standard`

* Class: `cao-2.2-service`
** Plan: `csb-basic`
** Plan: `csb-standard`

* Class: `cao-2.3-service`
** Plan: `csb-basic`
** Plan: `csb-standard`

* Class: `couchbase-autonomous-operator`
** Plan: `2.1.0`
** Plan: `2.2.0`
** Plan: `2.3.0`


Each `cao` service class has two service plans -- `csb-basic` and `csb-standard` -- for its respective version of the Autonomous Operator.
These service classes are provided on either a per-namespace or global basis.

NOTE: The `couchbase-autonomous-operator` class is not meant to be used directly, but is instead instantiated by the `cao` plans.
This design maintains a separation between Couchbase custom resources and the Autonomous Operator itself.

For more information, refer to the xref:install/get-started.adoc[Getting Started] guide.

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements^] page. Couchbase is thankful to all individuals who have created these third-party components.

== More Information

xref:operator::release-notes.adoc[Couchbase Autonomous Operator Release Notes]
