= Release Notes for Couchbase Service Broker 1.0

Couchbase Service Broker 1.0 provides the first native integration of Couchbase Autonomous Operator with Open Service Broker API for the Open Source Kubernetes platform.

Couchbase Service Broker 1.0 provides a service class named _couchbase-osb-service_ with two service plans: `csb-basic` and `csb-standard` (with the regular Couchbase Server Enterprise subscription), that will work with any version of Couchbase Autonomous Operator. However, we recommend using Couchbase Autonomous Operator version 2.1.

Take a look at the xref:service-broker::index.adoc[Getting Started] page to learn about Couchbase Service Broker in detail.

== Platform Support

Couchbase Service Broker 1.0 is supported only on the Open Source Kubernetes platform including AWS EKS, Azure AKS, and Google GKE.

For the latest platform support information, see xref:install/get-started.adoc#prerequisites[Prerequisites].

== Limitations

*  Red Hat OpenShift is not supported as Template Service Broker and Service Catalog have been deprecated and removed from the latest OpenShift releases.
* Couchbase Service Broker 1.0 supports Open Service Broker API 2.13. 

== Providing Feedback

You can have a big impact on future versions of the Couchbase Autonomous Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments on https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all individuals who have created these third-party components.

== More Information

xref:operator::release-notes.adoc[Release Notes: Couchbase Autonomous Operator for Kubernetes]
